
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  db:
    image: mysql:8
    container_name: db-w-61
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./db/data/:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: always

##########################################################################################################################

  whatsapp:
    image: python:3.10
    container_name: whatsapp-61
    build: ./whatsapp
    command: python -m .
    env_file: .env
    volumes:
      - ./whatsapp/:/usr/app/
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    depends_on:
      - db
    restart: always

##########################################################################################################################
