
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  db:
    image: melon-yellow/mysql-8-avb-whatsapp-py-db
    container_name: avb-whatsapp-py-db
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./db/data/:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: always

##########################################################################################################################

  whatsapp:
    image: melon-yellow/python-3.10-avb-whatsapp-py
    container_name: avb-whatsapp-py
    build: ./whatsapp
    command: bash -c "
      pip install -r requirements.txt &&
      cd .. &&
      python -m app"
    env_file: .env
    volumes:
      - ./whatsapp/:/usr/app/
      - /usr/local/lib/python3.10/site-packages/
    ports:
      - "${WHATSAPP_PORT}:${WHATSAPP_PORT}"
    depends_on:
      - db
    restart: always

##########################################################################################################################
